# Generated by Django 5.0.6 on 2024-05-18 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_finished', models.IntegerField()),
                ('items_found', models.IntegerField()),
                ('time_of_last_item_found', models.DateTimeField()),
                ('hunt_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.huntinstance')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='hunt_instances',
            field=models.ManyToManyField(through='main_app.Participation', to='main_app.huntinstance'),
        ),
        migrations.CreateModel(
            name='RiddleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riddle', models.CharField(max_length=100)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.item')),
            ],
        ),
        migrations.CreateModel(
            name='RiddleItemSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.participation')),
                ('riddle_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.riddleitem')),
            ],
        ),
        migrations.CreateModel(
            name='ScavengerHunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=1)),
                ('location', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='riddleitem',
            name='scavenger_hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.scavengerhunt'),
        ),
        migrations.AddField(
            model_name='huntinstance',
            name='scavenger_hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.scavengerhunt'),
        ),
    ]
